schema = 3

[mod]
  [mod."github.com/Masterminds/semver/v3"]
    version = "v3.4.0"
    hash = "sha256-75kRraVwYVjYLWZvuSlts4Iu28Eh3SpiF0GHc7vCYHI="
  [mod."github.com/containerd/stargz-snapshotter/estargz"]
    version = "v0.18.1"
    hash = "sha256-gfhN/OA+yptydsuQXL9F4S0rAfntUNnXvB2AZQhQJig="
  [mod."github.com/docker/cli"]
    version = "v29.0.3+incompatible"
    hash = "sha256-TUFZYeLpRPgPdOzmerLrKjNdl1N36evEVdcId6lH5nk="
  [mod."github.com/docker/distribution"]
    version = "v2.8.3+incompatible"
    hash = "sha256-XhRURCGNpJC83QZTtgCxHHFL76HaxIxjt70HwUa847E="
  [mod."github.com/docker/docker-credential-helpers"]
    version = "v0.9.3"
    hash = "sha256-HkmdB771ekeXa+XUzvmHIIfejS0E5k0zv3LVFuOevt4="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.3"
    hash = "sha256-Nnp/dEVNMxLp3RSPDHZzGbI8BkSNuZMX0I0cjWKXXLA="
  [mod."github.com/go-task/slim-sprig/v3"]
    version = "v3.0.0"
    hash = "sha256-vCCw4MXVBm33VNLXcOBccVDD1CSnzDvDdWB6w5FN1cA="
  [mod."github.com/google/go-cmp"]
    version = "v0.7.0"
    hash = "sha256-JbxZFBFGCh/Rj5XZ1vG94V2x7c18L8XKB0N9ZD5F2rM="
  [mod."github.com/google/go-containerregistry"]
    version = "v0.20.7"
    hash = "sha256-IkvePl7PwjCaHPealmpkxpqeNo7Cn1I/xzHyHV1x18c="
  [mod."github.com/google/pprof"]
    version = "v0.0.0-20250923004556-9e5a51aed1e8"
    hash = "sha256-kZmrxARFnMPJ/vA6YjKB8RDYUrfoNtIT8aw/ikL5a6Y="
  [mod."github.com/klauspost/compress"]
    version = "v1.18.1"
    hash = "sha256-nkL7v2/C66brSfYRPN8FXLtUXN2I7VZ+Obvyc6be+GA="
  [mod."github.com/mitchellh/go-homedir"]
    version = "v1.1.0"
    hash = "sha256-oduBKXHAQG8X6aqLEpqZHs5DOKe84u6WkBwi4W6cv3k="
  [mod."github.com/onsi/ginkgo/v2"]
    version = "v2.27.3"
    hash = "sha256-8rYXtDcKRStw+j1kXcAsMGxxRfszj3qRut1SxJHKI9k="
  [mod."github.com/onsi/gomega"]
    version = "v1.38.2"
    hash = "sha256-chit6Aia8qLfUfn/2stQmXG/nqM13fDN7edfixXBFsM="
  [mod."github.com/opencontainers/go-digest"]
    version = "v1.0.0"
    hash = "sha256-cfVDjHyWItmUGZ2dzQhCHgmOmou8v7N+itDkLZVkqkQ="
  [mod."github.com/opencontainers/image-spec"]
    version = "v1.1.1"
    hash = "sha256-bxBjtl+6846Ed3QHwdssOrNvlHV6b+Dn17zPISSQGP8="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.9.3"
    hash = "sha256-EnxsWdEUPYid+aZ9H4/iMTs1XMvCLbXZRDyvj89Ebms="
  [mod."github.com/spf13/afero"]
    version = "v1.15.0"
    hash = "sha256-LhcezbOqfuBzacytbqck0hNUxi6NbWNhifUc5/9uHQ8="
  [mod."github.com/vbatts/tar-split"]
    version = "v0.12.2"
    hash = "sha256-6gOHl4puCV9T2EWpFpqMCkV9N2PEPSiWbNZNp20q7iM="
  [mod."go.yaml.in/yaml/v3"]
    version = "v3.0.4"
    hash = "sha256-NkGFiDPoCxbr3LFsI6OCygjjkY0rdmg5ggvVVwpyDQ4="
  [mod."golang.org/x/mod"]
    version = "v0.30.0"
    hash = "sha256-tZJikWbjGgN5rCgB/dqj3dpn9BfAZUVyXmd3KavAgLE="
  [mod."golang.org/x/net"]
    version = "v0.47.0"
    hash = "sha256-2qFgCd0YfNCGkLrf+xvnhQtKjSe8CymMdLlN3svUYTg="
  [mod."golang.org/x/sync"]
    version = "v0.18.0"
    hash = "sha256-S8o6y7GOaYWeq+TzT8BB6T+1mg82Mu08V0TL3ukJprg="
  [mod."golang.org/x/sys"]
    version = "v0.38.0"
    hash = "sha256-1+i5EaG3JwH3KMtefzJLG5R6jbOeJM4GK3/LHBVnSy0="
  [mod."golang.org/x/text"]
    version = "v0.31.0"
    hash = "sha256-AT46RrSmV6+/d5FDhs9fPwYzmQ7WSo+YL9tPfhREwLw="
  [mod."golang.org/x/tools"]
    version = "v0.39.0"
    hash = "sha256-cCJLi3A7mhx7N7+fn0MbyDStf1dG2OPqu68bRMHpmw4="
  [mod."google.golang.org/protobuf"]
    version = "v1.36.9"
    hash = "sha256-i4zQhGFR6KprA5elLw33bA1VdMLAnL+Du3gBmrea+3Y="
