schema = 3

[mod]
  [mod."github.com/Masterminds/semver/v3"]
    version = "v3.4.0"
    hash = "sha256-75kRraVwYVjYLWZvuSlts4Iu28Eh3SpiF0GHc7vCYHI="
  [mod."github.com/containerd/stargz-snapshotter/estargz"]
    version = "v0.18.1"
    hash = "sha256-gfhN/OA+yptydsuQXL9F4S0rAfntUNnXvB2AZQhQJig="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.2-0.20180830191138-d8f796af33cc"
    hash = "sha256-fV9oI51xjHdOmEx6+dlq7Ku2Ag+m/bmbzPo6A4Y74qc="
  [mod."github.com/docker/cli"]
    version = "v29.0.3+incompatible"
    hash = "sha256-TUFZYeLpRPgPdOzmerLrKjNdl1N36evEVdcId6lH5nk="
  [mod."github.com/docker/distribution"]
    version = "v2.8.3+incompatible"
    hash = "sha256-XhRURCGNpJC83QZTtgCxHHFL76HaxIxjt70HwUa847E="
  [mod."github.com/docker/docker-credential-helpers"]
    version = "v0.9.3"
    hash = "sha256-HkmdB771ekeXa+XUzvmHIIfejS0E5k0zv3LVFuOevt4="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.3"
    hash = "sha256-Nnp/dEVNMxLp3RSPDHZzGbI8BkSNuZMX0I0cjWKXXLA="
  [mod."github.com/go-task/slim-sprig/v3"]
    version = "v3.0.0"
    hash = "sha256-vCCw4MXVBm33VNLXcOBccVDD1CSnzDvDdWB6w5FN1cA="
  [mod."github.com/google/go-cmp"]
    version = "v0.7.0"
    hash = "sha256-JbxZFBFGCh/Rj5XZ1vG94V2x7c18L8XKB0N9ZD5F2rM="
  [mod."github.com/google/go-containerregistry"]
    version = "v0.20.7"
    hash = "sha256-IkvePl7PwjCaHPealmpkxpqeNo7Cn1I/xzHyHV1x18c="
  [mod."github.com/google/pprof"]
    version = "v0.0.0-20251007162407-5df77e3f7d1d"
    hash = "sha256-iYCDdRPCFqOOy1LmErAIt8VxNq+jBeQHuWXy8gwRatk="
  [mod."github.com/klauspost/compress"]
    version = "v1.18.1"
    hash = "sha256-nkL7v2/C66brSfYRPN8FXLtUXN2I7VZ+Obvyc6be+GA="
  [mod."github.com/mitchellh/go-homedir"]
    version = "v1.1.0"
    hash = "sha256-oduBKXHAQG8X6aqLEpqZHs5DOKe84u6WkBwi4W6cv3k="
  [mod."github.com/onsi/ginkgo/v2"]
    version = "v2.27.3"
    hash = "sha256-8rYXtDcKRStw+j1kXcAsMGxxRfszj3qRut1SxJHKI9k="
  [mod."github.com/onsi/gomega"]
    version = "v1.38.3"
    hash = "sha256-dz6Q5L0Rxu/rhdLRz5iCrO+kpTTRFa09yGTBqWi5Bvs="
  [mod."github.com/opencontainers/go-digest"]
    version = "v1.0.0"
    hash = "sha256-cfVDjHyWItmUGZ2dzQhCHgmOmou8v7N+itDkLZVkqkQ="
  [mod."github.com/opencontainers/image-spec"]
    version = "v1.1.1"
    hash = "sha256-bxBjtl+6846Ed3QHwdssOrNvlHV6b+Dn17zPISSQGP8="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.1-0.20181226105442-5d4384ee4fb2"
    hash = "sha256-XA4Oj1gdmdV/F/+8kMI+DBxKPthZ768hbKsO3d9Gx90="
  [mod."github.com/rogpeppe/go-internal"]
    version = "v1.14.1"
    hash = "sha256-6NzhXCCD1Qhj05WHbCDxH5hwfNM6psoAk7uIxm7N55E="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.9.3"
    hash = "sha256-EnxsWdEUPYid+aZ9H4/iMTs1XMvCLbXZRDyvj89Ebms="
  [mod."github.com/spf13/afero"]
    version = "v1.15.0"
    hash = "sha256-LhcezbOqfuBzacytbqck0hNUxi6NbWNhifUc5/9uHQ8="
  [mod."github.com/stretchr/testify"]
    version = "v1.11.1"
    hash = "sha256-sWfjkuKJyDllDEtnM8sb/pdLzPQmUYWYtmeWz/5suUc="
  [mod."github.com/vbatts/tar-split"]
    version = "v0.12.2"
    hash = "sha256-6gOHl4puCV9T2EWpFpqMCkV9N2PEPSiWbNZNp20q7iM="
  [mod."go.yaml.in/yaml/v3"]
    version = "v3.0.4"
    hash = "sha256-NkGFiDPoCxbr3LFsI6OCygjjkY0rdmg5ggvVVwpyDQ4="
  [mod."golang.org/x/mod"]
    version = "v0.30.0"
    hash = "sha256-tZJikWbjGgN5rCgB/dqj3dpn9BfAZUVyXmd3KavAgLE="
  [mod."golang.org/x/net"]
    version = "v0.47.0"
    hash = "sha256-2qFgCd0YfNCGkLrf+xvnhQtKjSe8CymMdLlN3svUYTg="
  [mod."golang.org/x/sync"]
    version = "v0.19.0"
    hash = "sha256-RbRZ+sKZUurOczGhhzOoY/sojTlta3H9XjL4PXX/cno="
  [mod."golang.org/x/sys"]
    version = "v0.38.0"
    hash = "sha256-1+i5EaG3JwH3KMtefzJLG5R6jbOeJM4GK3/LHBVnSy0="
  [mod."golang.org/x/text"]
    version = "v0.32.0"
    hash = "sha256-9PXtWBKKY9rG4AgjSP4N+I1DhepXhy8SF/vWSIDIoWs="
  [mod."golang.org/x/tools"]
    version = "v0.39.0"
    hash = "sha256-cCJLi3A7mhx7N7+fn0MbyDStf1dG2OPqu68bRMHpmw4="
  [mod."google.golang.org/protobuf"]
    version = "v1.36.11"
    hash = "sha256-7W+6jntfI/awWL3JP6yQedxqP5S9o3XvPgJ2XxxsIeE="
  [mod."gopkg.in/check.v1"]
    version = "v1.0.0-20201130134442-10cb98267c6c"
    hash = "sha256-VlIpM2r/OD+kkyItn6vW35dyc0rtkJufA93rjFyzncs="
  [mod."gotest.tools/v3"]
    version = "v3.5.2"
    hash = "sha256-eAxnRrF2bQugeFYzGLOr+4sLyCPOpaTWpoZsIKNP1WE="
