name: go-containerregistry

on:
  push:
    # For code coverage reports
    branches: [main]
    paths:
      - .github/workflows/containerregistry.yml
      - containerregistry/*
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/containerregistry.yml
      - containerregistry/*

permissions:
  contents: read

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: containerregistry/go.mod
          cache-dependency-path: containerregistry/go.sum

      - run: |
          go -C containerregistry tool ginkgo run -r \
          --github-output \
          --race \
          --trace

  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31.9.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - run: nix build .#aferox-containerregistry
