name: GitHub

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/github.yml
      - github/*
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/github.yml
      - github/*

permissions:
  contents: read

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: github/go.mod
          cache-dependency-path: github/go.sum

      - run: |
          go -C github tool ginkgo run -r \
          --github-output \
          --race \
          --trace \
          --coverprofile=cover.profile
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          files: cover.profile
          name: aferox/github

  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31.9.0
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - run: nix build .#aferox-github
