name: gitignore

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/gitignore.yml
      - gitignore/*
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/gitignore.yml
      - gitignore/*


permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: gitignore/go.mod
          cache-dependency-path: gitignore/go.sum

      - run: |
          go -C gitignore tool ginkgo run -r \
          --github-output \
          --race \
          --trace \
          --coverprofile=cover.profile

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          files: cover.profile
          name: aferox/gitignore

  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31.9.1
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - run: nix build .#aferox-gitignore
