name: go-containerregistry

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/gitignore.yml
      - gitignore/*
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/gitignore.yml
      - gitignore/*

permissions:
  contents: read

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: gitignore/go.mod
          cache-dependency-path: gitignore/go.sum

      - run: |
          go -C gitignore tool ginkgo run -r \
          --github-output \
          --race \
          --trace

  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31.9.0
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - run: nix build .#aferox-gitignore
